[package]
name = "rusty_lisp"
version = "0.1.0"
authors = ["William Murphy <willmurphyscode@gmail.com>"]
build = "build.rs" # LALRPOP preprocessing


[dependencies]
regex = "0.1"
lalrpop-util = "0.12.0"


[build-dependencies]
lalrpop = "0.12.0"
