use std::str::FromStr;
use opcode;

grammar; 

pub SExpression : opcode::SExpression = {
    Num => opcode::SExpression::atomic(<>),
    "(" <o:OpCode> <v:Values> ")" => opcode::SExpression::op(
        opcode::Operation{ opcode : o, values : v }
    )
};

pub Values = Num+;


pub Num : f64 = r"((-)|(\+))?[0-9]+\.?[0-9]*" => f64::from_str(<>).unwrap();

pub OpCode : opcode::OpCode =  {
    "+" => opcode::OpCode::Add,
    "-" => opcode::OpCode::Subtract,
    "*" => opcode::OpCode::Multiply,
    "/" => opcode::OpCode::Divide,
};